version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: logs/app.log

loggers:
  root:
    level: INFO
    handlers: [console, file]

text_preprocessing:
  stop_words:
    - и
    - в
    - во
    - не
    - что
    - он
    - на
    - я
    - с
    - со
    - как
    - а
    - то
    - все
    - она
    - так
    - его
    - но
    - да
    - ты
    - к
    - у
    - же
    - вы
    - за
    - бы
    - по
    - только
    - ее
    - мне
    - было
    - вот
    - от
    - меня
    - еще
    - нет
    - о
    - из
    - ему
    - теперь
    - когда
    - даже
    - ну
    - вдруг
    - ли
    - если
    - уже
    - или
    - ни
    - быть
    - был
    - него
    - до
    - вас
    - нибудь
    - опять
    - уж
    - вам
    - ведь
    - там
    - потом
    - себя
    - ничего
    - ей
    - может
    - они
    - тут
    - где
    - есть
    - надо
    - ней
    - для
    - мы
    - тебя
    - их
    - чем
    - была
    - сам
    - чтоб
    - без
    - будто
    - чего
    - раз
    - тоже
    - себе
    - под
    - будет
    - ж
    - тогда
    - кто
    - этот
    - того
    - потому
    - этого
    - какой
    - совсем
    - ним
    - здесь
    - этом
    - один
    - почти
    - мой
    - тем
    - чтобы
    - нее
    - сейчас
    - были
    - куда
    - зачем
    - всех
    - никогда
    - можно
    - при
    - наконец
    - два
    - об
    - другой
    - хоть
    - после
    - над
    - больше
    - тот
    - через
    - эти
    - нас
    - про
    - всего
    - них
    - какая
    - много
    - разве
    - три
    - эту
    - моя
    - впрочем
    - хорошо
    - свою
    - этой
    - перед
    - иногда
    - лучше
    - чуть
    - том
    - нельзя
    - такой
    - им
    - более
    - всегда
    - конечно
    - всю
    - между

anonymization_patterns:
  phone: '(\+7|8)?\s?\(?\d{3}\)?\s?\d{3}-?\d{2}-?\d{2}'
  email: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
  card: '\b\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\b'
