version: 1
formatters:
  json:
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}'
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: logs/app.log
    maxBytes: 10485760
    backupCount: 5
root:
  level: INFO
  handlers: [console, file]


text_preprocessing:
  stop_words:
    - и
    - в
    - во
    - не
    - что
    - он
    - на
    - я
    - с
    - со
    - как
    - а
    - то
    - все
    - она
    - так
    - его
    - но
    - да
    - ты
    - к
    - у
    - же
    - вы
    - за
    - бы
    - по
    - только
    - ее
    - мне
    - было
    - вот
    - от
    - меня
    - еще
    - нет
    - о
    - из
    - ему
    - теперь
    - когда
    - даже
    - ну
    - вдруг
    - ли
    - если
    - уже
    - или
    - ни
    - быть
    - был
    - него
    - до
    - вас
    - нибудь
    - опять
    - уж
    - вам
    - ведь
    - там
    - потом
    - себя
    - ничего
    - ей
    - может
    - они
    - тут
    - где
    - есть
    - надо
    - ней
    - для
    - мы
    - тебя
    - их
    - чем
    - была
    - сам
    - чтоб
    - без
    - будто
    - чего
    - раз
    - тоже
    - себе
    - под
    - будет
    - ж
    - тогда
    - кто
    - этот
    - того
    - потому
    - этого
    - какой
    - совсем
    - ним
    - здесь
    - этом
    - один
    - почти
    - мой
    - тем
    - чтобы
    - нее
    - сейчас
    - были
    - куда
    - зачем
    - всех
    - никогда
    - можно
    - при
    - наконец
    - два
    - об
    - другой
    - хоть
    - после
    - над
    - больше
    - тот
    - через
    - эти
    - нас
    - про
    - всего
    - них
    - какая
    - много
    - разве
    - три
    - эту
    - моя
    - впрочем
    - хорошо
    - свою
    - этой
    - перед
    - иногда
    - лучше
    - чуть
    - том
    - нельзя
    - такой
    - им
    - более
    - всегда
    - конечно
    - всю
    - между
  anonymization_patterns:
    phone: '\\b(?:\\+7|8)?[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}\\b'
    account: '\\b\\d{16,20}\\b'
    email: '\\b[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,4}\\b'

