version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "module": "%(module)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/app.log
    maxBytes: 1000000
    backupCount: 3
    encoding: utf-8

loggers:
  root:
    level: INFO
    handlers: [console, file]

# Паттерны анонимизации
anonymization_patterns:
  phone: '(\+7|8)?\s?\(?\d{3}\)?\s?\d{3}-?\d{2}-?\d{2}'
  email: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
  card: '\b\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\b'
  account: '\b\d{20}\b'
