# Базовая конфигурация для банковского NLP проекта

data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  synthetic_data_path: "data/synthetic"
  models_path: "models"

model:
  base_model: "sberbank-ai/ruBERT-base"
  max_sequence_length: 512
  batch_size: 32
  learning_rate: 2e-5
  num_epochs: 3
  random_seed: 42
  device: "auto"  # auto, cpu, cuda

banking:
  topics:
    - "кредиты"
    - "депозиты"
    - "карты"
    - "переводы"
    - "инвестиции"
    - "страхование"
    - "ипотека"
    - "автокредит"
    - "потребительский_кредит"
    - "интернет_банк"
    - "мобильное_приложение"
    - "техподдержка"
  products:
    - "дебетовая_карта"
    - "кредитная_карта"
    - "срочный_депозит"
    - "накопительный_счет"
    - "потребительский_кредит"
    - "ипотека"
    - "автокредит"
    - "рефинансирование"
    - "овердрафт"

preprocessing:
  remove_urls: true
  remove_emails: true
  remove_phones: true
  normalize_whitespace: true
  min_text_length: 10
  max_text_length: 2048
  enable_spell_check: false

logging:
  level: "INFO"
  log_file: "logs/banking_nlp.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
